// source: people.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.demo.Person');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.demo.Address');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.demo.Person = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.demo.Person.repeatedFields_, null);
};
goog.inherits(proto.demo.Person, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.demo.Person.displayName = 'proto.demo.Person';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.demo.Person.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.demo.Person.prototype.toObject = function(opt_includeInstance) {
  return proto.demo.Person.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.demo.Person} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.demo.Person.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    addressList: jspb.Message.toObjectList(msg.getAddressList(),
    proto.demo.Address.toObject, includeInstance),
    mobileList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    emailList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.demo.Person}
 */
proto.demo.Person.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.demo.Person;
  return proto.demo.Person.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.demo.Person} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.demo.Person}
 */
proto.demo.Person.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.demo.Address;
      reader.readMessage(value,proto.demo.Address.deserializeBinaryFromReader);
      msg.addAddress(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addMobile(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.demo.Person.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.demo.Person.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.demo.Person} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.demo.Person.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddressList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.demo.Address.serializeBinaryToWriter
    );
  }
  f = message.getMobileList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getEmailList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.demo.Person.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.demo.Person} returns this
 */
proto.demo.Person.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Address address = 2;
 * @return {!Array<!proto.demo.Address>}
 */
proto.demo.Person.prototype.getAddressList = function() {
  return /** @type{!Array<!proto.demo.Address>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.demo.Address, 2));
};


/**
 * @param {!Array<!proto.demo.Address>} value
 * @return {!proto.demo.Person} returns this
*/
proto.demo.Person.prototype.setAddressList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.demo.Address=} opt_value
 * @param {number=} opt_index
 * @return {!proto.demo.Address}
 */
proto.demo.Person.prototype.addAddress = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.demo.Address, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.demo.Person} returns this
 */
proto.demo.Person.prototype.clearAddressList = function() {
  return this.setAddressList([]);
};


/**
 * repeated string mobile = 3;
 * @return {!Array<string>}
 */
proto.demo.Person.prototype.getMobileList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.demo.Person} returns this
 */
proto.demo.Person.prototype.setMobileList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.demo.Person} returns this
 */
proto.demo.Person.prototype.addMobile = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.demo.Person} returns this
 */
proto.demo.Person.prototype.clearMobileList = function() {
  return this.setMobileList([]);
};


/**
 * repeated string email = 4;
 * @return {!Array<string>}
 */
proto.demo.Person.prototype.getEmailList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.demo.Person} returns this
 */
proto.demo.Person.prototype.setEmailList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.demo.Person} returns this
 */
proto.demo.Person.prototype.addEmail = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.demo.Person} returns this
 */
proto.demo.Person.prototype.clearEmailList = function() {
  return this.setEmailList([]);
};


